vich_uploader:
    db_driver: orm

    mappings:
        picture:
            uri_prefix: /images/picture
            upload_destination: '%kernel.project_dir%/assets/images/picture'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
